apiVersion: v1
kind: Service
metadata:
  name: myjajaapp-svc
  labels:
    app: myjavaapp-pod
    apiVersion: 2.6.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp-pod
    apiVersion: 2.6.2
  
