apiVersion: v1
kind: Service
metadata:
  name: myjajaapp-svc
  labels:
    app: myjavaapp-pod
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp-pod
  
